name: nodejs

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [
          '16',
          '18',
          '20'
        ]

    name: Node JS ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm install
      - name: Test
        run: npm test

      - name: Publish
        if: startsWith(github.ref, 'refs/tags') && matrix.node == '20'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISHER_TOKEN }}
